# This configuration file should contain all required configuration parameters
# for the ingest workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

# Required to fetch from Entrez
entrez_search_term: ""

# Supply information specific to each virus
229e:
    # NCBI Taxon ID
    # Required to fetch from NCBI Datasets
    ncbi_taxon_id: "11137"
    # Path to the manual annotations file
    # The path should be relative to the ingest directory
    annotations: "config/229e/annotations.tsv"
nl63:
    # NCBI Taxon ID
    # Required to fetch from NCBI Datasets
    ncbi_taxon_id: "277944"
    # Path to the manual annotations file
    # The path should be relative to the ingest directory
    annotations: "config/nl63/annotations.tsv"

# Optional fields to add to the NCBI Datasets output
ncbi_dataset_fields: []

# Config parameters related to the curate pipeline
# Shared by all viruses
curate:
  # URL pointed to public generalized geolocation rules
  # For the Nextstrain team, this is currently
  # 'https://raw.githubusercontent.com/nextstrain/ncov-ingest/master/source-data/gisaid_geoLocationRules.tsv'
  geolocation_rules_url: "https://raw.githubusercontent.com/nextstrain/ncov-ingest/master/source-data/gisaid_geoLocationRules.tsv"
  # The path to the local geolocation rules within the pathogen repo
  # The path should be relative to the ingest directory.
  local_geolocation_rules: "config/geolocation_rules.tsv"
  # List of field names to change in the format of <old_field_name>=<new_field_name>
  # This is the first step in the pipeline, so any references to field names
  # in the configs below should use the new field names
  field_map: ['Accession=strain', "'Isolate Lineage'=name", "'Geographic Region'=region", "'Geographic Location'=country", "'Isolate Collection date'=date", "'Host Name'=host", "'Submitter Names'=authors", "'Submitter Affiliation'=institution", "'SRA Accessions'=sra_accession", "passage_type=passage_type"]
  # List of date fields to standardize to ISO format YYYY-MM-DD
  date_fields: ['date']
  # List of expected date formats that are present in the date fields provided above
  # These date formats should use directives expected by datetime
  # See https://docs.python.org/3.9/library/datetime.html#strftime-and-strptime-format-codes
  expected_date_formats: ['%Y', '%Y-%m', '%Y-%m-%d', '%Y-%m-%dT%H:%M:%SZ']
  titlecase:
    # Abbreviations not cast to titlecase, keeps uppercase
    abbreviations: ['USA']
    # Articles that should not be cast to titlecase
    articles: [
      'and', 'd', 'de', 'del', 'des', 'di', 'do', 'en', 'l', 'la', 'las', 'le',
      'los', 'nad', 'of', 'op', 'sur', 'the', 'y'
    ]
    # List of string fields to titlecase
    fields: ['region', 'country', 'division', 'location']
  # Metadata field that contains the list of authors associated with the sequence
  authors_field: "authors"
  # Default value to use if the authors field is empty
  authors_default_value: "?"
  # Name to use for the generated abbreviated authors field
  abbr_authors_field: "abbr_authors"
  # The ID field in the metadata to use to merge the manual annotations
  annotations_id: "strain"
  # The ID field in the metadata to use as the sequence id in the output FASTA file
  output_id_field: "strain"
  # The field in the NDJSON record that contains the actual genomic sequence
  output_sequence_field: "sequence"
  # The list of metadata columns to keep in the final output of the curation pipeline.
  metadata_columns: 
    - strain
    - name
    - date
    - region
    - country
    - host
    - passage_type
    - sra_accession
    - abbr_authors
    - authors
    - institution