# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "defaults/config.yaml"


rule all:
    input:
        expand("auspice/seasonal-cov_{virus}.json", virus=config["viruses"]),


include: "rules/prepare_sequences.smk"
include: "rules/construct_phylogeny.smk"
include: "rules/annotate_phylogeny.smk"
include: "rules/export.smk"


rule clean:
    params:
        targets = [
            ".snakemake",
            "auspice",
            "data",
            "logs",
            "results",
            ]
    shell:
        r"""
        rm -rfv {params.targets}
        """


# Import custom rules provided via the config.
if "custom_rules" in config:
    for rule_file in config["custom_rules"]:

        include: rule_file
