VIRUSES = ["229e", "nl63", "oc43", "hku1"]


rule all:
    input:
        expand("auspice/{virus}.json", virus=VIRUSES),


# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "config/defaults.yaml"


include: "rules/prepare_sequences.smk"
include: "rules/construct_phylogeny.smk"
include: "rules/annotate_phylogeny.smk"
include: "rules/export.smk"
