# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "config/defaults.yaml"


rule all:
    input:
        expand("auspice/{virus}.json", virus=config["viruses"]),


include: "rules/prepare_sequences.smk"
include: "rules/construct_phylogeny.smk"
include: "rules/annotate_phylogeny.smk"
include: "rules/export.smk"
