# virus species in this dataset
# NOTE: when adding a new species, you must also add a top level key
# with the species name pointing to specific information.
viruses:
  - "229e"
  - "nl63"
  - "oc43"
  - "hku1"

# virus-specific information
# For each virus, provide the following parameter values. All paths
# should be relative to the phylogenetic directory.
#
# reference = path to local reference sequence
# genemap = path to local GFF genemap
# metadata = path to metadata.tsv
# prepare_sequences = parameters related to sequence prep pipeline
#   sequences = path to the sequence FASTA file
#   # augur filter param values:
#   group_by
#   subsample_max_sequences
#   min_length
# construct_phylogeny = parameters related to tree building pipeline
#   # augur refine param values
#   clock_rate
#   clock_std_dev
#   coalescent
#   date_inference
#   clock_filter_iq
# annotate_phylogeny = parameters related to tree annotation pipeline
#   inference = ancestral sequence reconstruction param
#   columns = ancestral traits param
229e:
  reference: "defaults/229e/reference.fasta"
  genemap: "defaults/229e/genemap.gff"
  prepare_sequences:
    group_by: "country"
    subsample_max_sequences: 4000
    min_length: 20000
  construct_phylogeny:
    clock_rate: 0.000250
    clock_std_dev: 0.00010
    coalescent: "opt"
    date_inference: "marginal"
    clock_filter_iqd: 4
  annotate_phylogeny:
    inference: "joint"
nl63:
  reference: "defaults/nl63/reference.fasta"
  genemap: "defaults/nl63/genemap.gff"
  prepare_sequences:
    group_by: "country"
    subsample_max_sequences: 4000
    min_length: 20000
  construct_phylogeny:
    clock_rate: 0.000120
    clock_std_dev: 0.00005
    coalescent: "opt"
    date_inference: "marginal"
    clock_filter_iqd: 4
  annotate_phylogeny:
    inference: "joint"
oc43:
  reference: "defaults/oc43/reference.fasta"
  genemap: "defaults/oc43/genemap.gff"
  prepare_sequences:
    group_by: "country"
    subsample_max_sequences: 4000
    min_length: 20000
  construct_phylogeny:
    clock_rate: 0.000250
    clock_std_dev: 0.00010
    coalescent: "opt"
    date_inference: "marginal"
    clock_filter_iqd: 4
  annotate_phylogeny:
    inference: "joint"
hku1:
  reference: "defaults/hku1/reference.fasta"
  genemap: "defaults/hku1/genemap.gff"
  prepare_sequences:
    group_by: "country"
    subsample_max_sequences: 4000
    min_length: 20000
  construct_phylogeny:
    clock_rate: 0.000120
    clock_std_dev: 0.00005
    coalescent: "opt"
    date_inference: "marginal"
    clock_filter_iqd: 4
  annotate_phylogeny:
    inference: "joint"
